twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/category': category
        '%kernel.project_dir%/templates/components': components
        '%kernel.project_dir%/templates/guideline': guideline
        '%kernel.project_dir%/templates/customer': customer
        '%kernel.project_dir%/templates/product': product
        '%kernel.project_dir%/templates/base': base
        '%kernel.project_dir%/templates/user': user
        '%kernel.project_dir%/templates/quote': quote
        '%kernel.project_dir%/templates/bill': bill
    form_themes:
        - 'components/form/custom_theme.html.twig'

when@test:
    twig:
        strict_variables: true
