vich_uploader:
    db_driver: orm

    mappings:
        avatar:
          uri_prefix: /upload/image/user/profile
          upload_destination: '%kernel.project_dir%/public/upload/image/user/profile'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

          inject_on_load: true
          delete_on_update: true
          delete_on_remove: true
