version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    expose:
      - 9000
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-group12}:${POSTGRES_PASSWORD:-root}@database:5432/${POSTGRES_DB:-challenges1}?serverVersion=${POSTGRES_VERSION:-13}
      XDEBUG_CONFIG: remote_host=host.docker.internal
    ports:
      - "8000:80"

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-challenges1}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-group12}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - "3000:8080"
    depends_on:
      - database

volumes:
  php_socket:
  db_data:
